export const weatherImages = {
    "01n": require("../assets/images/half-moon.png"),
    "01d": require("../assets/images/sun.png"),
    "02n": require("../assets/images/cloudy.png"),
    "02d": require("../assets/images/cloudy.png"),
    "03n": require("../assets/images/cloud1.png"),
    "03d": require("../assets/images/cloud1.png"),
    "04n": require("../assets/images/cloud.png"),
    "04d": require("../assets/images/cloud.png"),
    "09n": require("../assets/images/rain.png"),
    "09d": require("../assets/images/rain.png"),
    "10n": require("../assets/images/partialrain.png"),
    "10d": require("../assets/images/partialrain.png"),
    "11n": require("../assets/images/heavy-rain.png"),
    "11d": require("../assets/images/heavy-rain.png"),
    "13n": require("../assets/images/snow.png"),
    "13d": require("../assets/images/snow.png"),
    "50n": require("../assets/images/fog.png"),
    "50d": require("../assets/images/fog.png"),
}